service: telegram-lambdas
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  bot:
    handler: handler.bot
    events:
      - http:
          path: nodde-tg-bot
          method: post     
  bindChat:
    handler: bind-chat.bindChat
    events:
      - http:
          path: bind-chat
          method: post        
  inviteCodePrepare:
    handler: invite-code-prepare.prepareInvite
    events:
      - http:
          path: prepare-invite
          method: post
  inviteCodeGet:
    handler: invite-code-get.getInviteCode
    events:
      - http:
          path: get-invite-code    
          method: get

resources:
  Resources:
    communityTelegram:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Community-telegram
        KeySchema:
          - AttributeName: code
            KeyType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10    
    communityTelegramPrivateChat:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Community-telegram-private-chats
        KeySchema:
          - AttributeName: "user_id"
            KeyType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10        