service: telegram-lambdas
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  bot:
    handler: handler.bot
    events:
      - http:
          path: nodde-tg-bot
          method: post     
  bind:
    handler: bind.bind
    events:
      - http:
          path: bind
          method: post        
  inviteCodePrepare:
    handler: invite-code-prepare.prepareInvite
    events:
      - http:
          path: prepare-invite
  inviteCodeGet:
    handler: invite-code-get.getInviteCode
    events:
      - http:
          path: /get-invite-code    